### ISSUE TITLE
Not loading all of the streams 

### ISSUE THREAD

**Issue by Johelectrix09** [luongz/iptv-jp#36]
Hello there can I ask what happen to the japanese streams for now because this week is all working until now and all of the streams including HD and non HD aren't working and it 
only appeared not playing; is it updating or it was been closed??

**Comment by Johelectrix09** [comment]
Thank you for replying and I will always appreciate your efforts to make streams better

**Comment by luongz** [comment]
Our domain have some problem. Please wait until the problem solved. If the
list are working again , i will told you. Thanks!

Vào Th 6, 14 thg 7, 2023 lúc 13:30 Johelectrix09 ***@***.***>
đã viết:

**Comment by Johelectrix09** [comment]
Ohh ok I just need some clarifications to the problems the only one that I needed to watch is tomorrow but now I am patiently waiting for your services I thought it was closed down but anyways thanks and regards.

**Comment by luongz** [comment]
fixed

**Comment by Johelectrix09** [comment]
sir what happened is it still a domain problem

**Comment by Johelectrix09** [comment]
CS 2 Still doesn't playing since this morning it said no anonymous access

**Comment by Johelectrix09** [comment]
Is it because I'm abroad and not in Vietnam or is it just because of you're catching up links

**Comment by Azrael-001** [comment]
I'm sorry, it seems v1 is down just now

**Comment by luongz** [comment]
> I'm sorry, it seems v1 is down just now

fixed

**Comment by luongz** [comment]
> Sir it seems like I was restricted by watching these streams what did I do wrong

idk , try using vpn

![Screenshot_20230718-203536](https://github.com/luongz/iptv-jp/assets/76716526/f794beff-4fb9-432d-9a8c-52000e82e7d8)

**Comment by Johelectrix09** [comment]
ok thanks

**Comment by Johelectrix09** [comment]
I got an error when visiting code.vthanhtivi.pw/getlink/jptv1/4O3P2VsYGiDOYYHUKuF_1Q==/playlist.m3u8.

Error code: 1020

Ray ID: 7e8b25fb7c2004ea

Country: PH

Data center: hkg09

IP: 180.191.184.177

Timestamp: 2023-07-18 13:42:30 UTC

this is what appeared I can't take a screenshot so as doing vpn

**Comment by Johelectrix09** [comment]
ok fixed
